### ISSUE TITLE
requireindex issue in npm release (version 0.0.2)

### ISSUE THREAD

**Issue by jgarber623** [duhaime/eslint-plugin-frontmatter#1]
Hello! First off, thanks for this helpful module. A quick question about an issue I'm seeing:

In cb682cf, you properly corrected `requireIndex` to `requireindex`. However, what I'm seeing in the module that's downloaded from npm is the old, camelCased `requireIndex`.

I'm guessing that change wasn't published to npm (as version 0.0.3, maybe?). Is that the case? If so, could you publish an updated version of the module?

### Steps to Reproduce

1. Install the module via npm `npm install -g eslint eslint-plugin-frontmatter` (globally or locally, doesn't matter)
2. `cat ~/.nvm/versions/node/v9.8.0/lib/node_modules/eslint-plugin-frontmatter/lib/processors/frontmatter.js` (path to the module itself will vary, of course)
3. Observe line 1 reads `var requireIndex = require('requireIndex');`.

Thanks for your help!

**Comment by duhaime** [comment]
@jgarber623 Thanks for your note! I just published 0.0.3 to npm. You should be able to update with:

```
npm install eslint-plugin-frontmatter@0.0.3 --save
```
If that looks good, feel free to close this issue! Else I'm happy to follow up...

**Comment by duhaime** [comment]
@jgarber623 P.S. [The Orchid](https://theorchid.bandcamp.com/album/apogee-perigee) sounds awesome!

**Comment by jgarber623** [comment]
> If that looks good, feel free to close this issue!

@duhaime That did the trick. Thanks for the quick fix!

> P.S. The Orchid sounds awesome!

Thanks! Glad you're enjoying the record. That was a fun one to make. 😀

**Comment by duhaime** [comment]
@jgarber623 Awesome, thanks for following up!
